<?php echo $this->headTitle('Request/Upload');
$this->headLink()
    ->appendStylesheet($this->basePath() . '/components/plupload/js/jquery.ui.plupload/css/jquery.ui.plupload.css');
$this->inlineScript()
    ->offsetSetFile(101, $this->basePath() . '/components/plupload/js/plupload.full.min.js')
    ->offsetSetFile(102, $this->basePath() . '/components/plupload/js/jquery.ui.plupload/jquery.ui.plupload.min.js')
    ->offsetSetFile(103, $this->basePath() . '/components/plupload/js/i18n/ru.js')
    ->offsetSetFile(104, $this->basePath() . '/js/dmn/upload1.js');
?>
<div id="content">
    <table id="requestorg">
        <tr>
            <td></td>
        </tr>
    </table>
    <div id="uploader" data-href="<?php echo $this->url('dmnupload') ?>">
        <p>Your browser doesn't have Flash, Silverlight or HTML5 support.</p>
    </div>
</div>

