<?php

namespace DoctrineORMModule\Proxy\__CG__\DmnDatabase\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CciRequest extends \DmnDatabase\Entity\CciRequest implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'DmnDatabase\\Entity\\CciRequest' . "\0" . 'id', '' . "\0" . 'DmnDatabase\\Entity\\CciRequest' . "\0" . 'consignor', '' . "\0" . 'DmnDatabase\\Entity\\CciRequest' . "\0" . 'exporter', '' . "\0" . 'DmnDatabase\\Entity\\CciRequest' . "\0" . 'consignee', '' . "\0" . 'DmnDatabase\\Entity\\CciRequest' . "\0" . 'importer', '' . "\0" . 'DmnDatabase\\Entity\\CciRequest' . "\0" . 'transport', '' . "\0" . 'DmnDatabase\\Entity\\CciRequest' . "\0" . 'servicemark', '' . "\0" . 'DmnDatabase\\Entity\\CciRequest' . "\0" . 'adressconsignor', '' . "\0" . 'DmnDatabase\\Entity\\CciRequest' . "\0" . 'adressexporter', '' . "\0" . 'DmnDatabase\\Entity\\CciRequest' . "\0" . 'adressconsignee', '' . "\0" . 'DmnDatabase\\Entity\\CciRequest' . "\0" . 'adressimporter', '' . "\0" . 'DmnDatabase\\Entity\\CciRequest' . "\0" . 'itinerary', '' . "\0" . 'DmnDatabase\\Entity\\CciRequest' . "\0" . 'unpconsignor', '' . "\0" . 'DmnDatabase\\Entity\\CciRequest' . "\0" . 'unpexporter', '' . "\0" . 'DmnDatabase\\Entity\\CciRequest' . "\0" . 'representation', '' . "\0" . 'DmnDatabase\\Entity\\CciRequest' . "\0" . 'fioagent', '' . "\0" . 'DmnDatabase\\Entity\\CciRequest' . "\0" . 'sertificatenumid'];
        }

        return ['__isInitialized__', '' . "\0" . 'DmnDatabase\\Entity\\CciRequest' . "\0" . 'id', '' . "\0" . 'DmnDatabase\\Entity\\CciRequest' . "\0" . 'consignor', '' . "\0" . 'DmnDatabase\\Entity\\CciRequest' . "\0" . 'exporter', '' . "\0" . 'DmnDatabase\\Entity\\CciRequest' . "\0" . 'consignee', '' . "\0" . 'DmnDatabase\\Entity\\CciRequest' . "\0" . 'importer', '' . "\0" . 'DmnDatabase\\Entity\\CciRequest' . "\0" . 'transport', '' . "\0" . 'DmnDatabase\\Entity\\CciRequest' . "\0" . 'servicemark', '' . "\0" . 'DmnDatabase\\Entity\\CciRequest' . "\0" . 'adressconsignor', '' . "\0" . 'DmnDatabase\\Entity\\CciRequest' . "\0" . 'adressexporter', '' . "\0" . 'DmnDatabase\\Entity\\CciRequest' . "\0" . 'adressconsignee', '' . "\0" . 'DmnDatabase\\Entity\\CciRequest' . "\0" . 'adressimporter', '' . "\0" . 'DmnDatabase\\Entity\\CciRequest' . "\0" . 'itinerary', '' . "\0" . 'DmnDatabase\\Entity\\CciRequest' . "\0" . 'unpconsignor', '' . "\0" . 'DmnDatabase\\Entity\\CciRequest' . "\0" . 'unpexporter', '' . "\0" . 'DmnDatabase\\Entity\\CciRequest' . "\0" . 'representation', '' . "\0" . 'DmnDatabase\\Entity\\CciRequest' . "\0" . 'fioagent', '' . "\0" . 'DmnDatabase\\Entity\\CciRequest' . "\0" . 'sertificatenumid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CciRequest $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setConsignor($consignor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConsignor', [$consignor]);

        return parent::setConsignor($consignor);
    }

    /**
     * {@inheritDoc}
     */
    public function getConsignor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConsignor', []);

        return parent::getConsignor();
    }

    /**
     * {@inheritDoc}
     */
    public function setExporter($exporter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExporter', [$exporter]);

        return parent::setExporter($exporter);
    }

    /**
     * {@inheritDoc}
     */
    public function getExporter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExporter', []);

        return parent::getExporter();
    }

    /**
     * {@inheritDoc}
     */
    public function setConsignee($consignee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConsignee', [$consignee]);

        return parent::setConsignee($consignee);
    }

    /**
     * {@inheritDoc}
     */
    public function getConsignee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConsignee', []);

        return parent::getConsignee();
    }

    /**
     * {@inheritDoc}
     */
    public function setImporter($importer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImporter', [$importer]);

        return parent::setImporter($importer);
    }

    /**
     * {@inheritDoc}
     */
    public function getImporter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImporter', []);

        return parent::getImporter();
    }

    /**
     * {@inheritDoc}
     */
    public function setTransport($transport)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTransport', [$transport]);

        return parent::setTransport($transport);
    }

    /**
     * {@inheritDoc}
     */
    public function getTransport()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransport', []);

        return parent::getTransport();
    }

    /**
     * {@inheritDoc}
     */
    public function setServicemark($servicemark)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setServicemark', [$servicemark]);

        return parent::setServicemark($servicemark);
    }

    /**
     * {@inheritDoc}
     */
    public function getServicemark()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServicemark', []);

        return parent::getServicemark();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdressconsignor($adressconsignor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdressconsignor', [$adressconsignor]);

        return parent::setAdressconsignor($adressconsignor);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdressconsignor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdressconsignor', []);

        return parent::getAdressconsignor();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdressexporter($adressexporter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdressexporter', [$adressexporter]);

        return parent::setAdressexporter($adressexporter);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdressexporter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdressexporter', []);

        return parent::getAdressexporter();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdressconsignee($adressconsignee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdressconsignee', [$adressconsignee]);

        return parent::setAdressconsignee($adressconsignee);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdressconsignee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdressconsignee', []);

        return parent::getAdressconsignee();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdressimporter($adressimporter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdressimporter', [$adressimporter]);

        return parent::setAdressimporter($adressimporter);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdressimporter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdressimporter', []);

        return parent::getAdressimporter();
    }

    /**
     * {@inheritDoc}
     */
    public function setItinerary($itinerary)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItinerary', [$itinerary]);

        return parent::setItinerary($itinerary);
    }

    /**
     * {@inheritDoc}
     */
    public function getItinerary()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItinerary', []);

        return parent::getItinerary();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnpconsignor($unpconsignor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnpconsignor', [$unpconsignor]);

        return parent::setUnpconsignor($unpconsignor);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnpconsignor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnpconsignor', []);

        return parent::getUnpconsignor();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnpexporter($unpexporter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnpexporter', [$unpexporter]);

        return parent::setUnpexporter($unpexporter);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnpexporter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnpexporter', []);

        return parent::getUnpexporter();
    }

    /**
     * {@inheritDoc}
     */
    public function setRepresentation($representation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRepresentation', [$representation]);

        return parent::setRepresentation($representation);
    }

    /**
     * {@inheritDoc}
     */
    public function getRepresentation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRepresentation', []);

        return parent::getRepresentation();
    }

    /**
     * {@inheritDoc}
     */
    public function setFioagent($fioagent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFioagent', [$fioagent]);

        return parent::setFioagent($fioagent);
    }

    /**
     * {@inheritDoc}
     */
    public function getFioagent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFioagent', []);

        return parent::getFioagent();
    }

    /**
     * {@inheritDoc}
     */
    public function setSertificatenumid(\DmnDatabase\Entity\CciRequestNumber $sertificatenumid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSertificatenumid', [$sertificatenumid]);

        return parent::setSertificatenumid($sertificatenumid);
    }

    /**
     * {@inheritDoc}
     */
    public function getSertificatenumid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSertificatenumid', []);

        return parent::getSertificatenumid();
    }

}
