<?php echo $this->headTitle($this->translate('Users'));
$this->inlineScript()
    ->offsetSetFile(101, $this->basePath('/js/dmn/indexu1.js'));
?>
<div id="content">
    <table id="orguser">
        <tr>
            <td></td>
        </tr>
    </table>
    <div id="porguser"></div>
    <div id="gridWrapper">
        <table id="user">
            <tr>
                <td></td>
            </tr>
        </table>
        <div id="puser"></div>
    </div>
</div>
