<?php echo $this->headTitle($this->translate('Add Request')); ?>
<div id="content">
<table id="requestlist"><tr><td></td></tr></table> 
<table id="requestlist_d"><tr><td></td></tr></table> 
<div id="prequestlist_d"></div>
	<div class="form-group">
		<input type="button" id="add" class ="btn btn-info addbutton" value="Отправить заявку" />
	</div>
</div>

<?php 
$this->inlineScript()->captureStart();
echo <<<JS
   $(function () {
		var lastSel;				
	  	$("#requestlist").jqGrid({
			regional : 'ru', 	  		
	  		url:'getaddrequest', 
	  		datatype: "json", 
	  		colNames:['Наименование','Значение'], 
	  		colModel:[ 
	  		           {name:'name',index:'name', editable:false, sortable:false, width:400}, 
	  		           {name:'value',index:'value', editable:true, editrules:{custom: true, 
																			  custom_func: function (value) {
            																	return validReq(value,  jQuery("#requestlist").jqGrid('getGridParam','selrow'));
        																	 }
																		 	}, 
						edittype:"text",  sortable:false, width:560}, 
					   	           
	  		         ],			
	  		rowNum:15,	
	  		sortname: 'item', 
	  		autowidth: true,
            shrinkToFit: true,
	  		height: '100%',
			viewrecords: true, 
	  		sortorder: "asc", 
	  		multiselect: false,
			onSelectRow: function(id){ 
      			if(id && id!==lastSel){ 
					jQuery('#requestlist').jqGrid('restoreRow',lastSel);         			
         			lastSel=id; 
      			} 
				jQuery('#requestlist').jqGrid('editRow',id,true);      			
   			}, 
			editurl: "addrequest",
	  		caption:"Добавление заявки"	  		
	  	});	
		$("#requestlist_d").jqGrid("clearGridData", true).trigger("reloadGrid");
		$("#requestlist_d").jqGrid({
			regional : 'ru', 	  		
	  		url:'getaddrequestdesc', 
	  		datatype: "json", 
	  		colNames:['Id','П/н №', 'К-во мест и вид упак.', 'Описание товара','Критерий', 'Кол-во товара', 'Ед.изм.', 'Номер и дата счета-фактуры'], 
	  		colModel:[ {name:'id',index:'id', width:'2%', hidden: true}, 
	  		           {name:'paragraph',index:'paragraph', width:'5%', editable:true}, 
	  		           {name:'seats',index:'seats', width:'20%', editable:true}, 
	  		           {name:'description',index:'description', width:'32%', editable:true, edittype:"textarea", editoptions:{rows:"3",cols:"30"}}, 
	  		           {name:'hscode',index:'hscode', width:'6%', editable:true}, 
	  		           {name:'quantity',index:'quantity', width:'15%', editable:true}, 
	  		           {name:'unit',index:'unit', width:'10%', editable:true}, 
	  		           {name:'invoce',index:'invoce', width:'10%', editable:true}  		           
	  		         ], 
	  		rowNum:10,
	  		autowidth: true,
            shrinkToFit: true, 
	  		height: '100%',
	  		rowList:[10,20,30], 
	  		pager: '#prequestlist_d', 
	  		sortname: 'item', 
	  		viewrecords: true, 
	  		sortorder: "asc", 
	  		multiselect: false, 
			editurl: "addrequestdesc",
	  		caption:"Дополнительная информация по заявке"	  		
	  	}); 
	  	$("#requestlist_d").jqGrid('navGrid','#prequestlist_d',{add:true,edit:true,del:false, search:false}, 
	  	{
            closeAfterEdit: true,			
            width: '50%',    
            reloadAfterSubmit:true,
			beforeShowForm: function (form) {				
				var dlgDiv = $("#editmodrequestlist_d");
        		var parentDiv = dlgDiv.parent(); 
        		var dlgWidth = dlgDiv.width();
        		var parentWidth = parentDiv.width();        		
        		var parentLeft = parentDiv.offset().left; 
				dlgDiv[0].style.top =  "100px";         		
        		dlgDiv[0].style.left = Math.round(  parentLeft + (parentWidth-dlgWidth  )/2 )  + "px";
		  },
        },
        {
            closeAfterAdd: true,
			rowID : "new_row",
			position: "last",
        	useDefValues: true,
            width: '50%',   
            reloadAfterSubmit:true,
			beforeShowForm: function (form) {				
				var dlgDiv = $("#editmodrequestlist_d");
        		var parentDiv = dlgDiv.parent(); 
        		var dlgWidth = dlgDiv.width();
        		var parentWidth = parentDiv.width();        		
        		var parentLeft = parentDiv.offset().left;  
				dlgDiv[0].style.top =  "100px";        		
        		dlgDiv[0].style.left = Math.round(  parentLeft + (parentWidth-dlgWidth  )/2 )  + "px";
		  },
        }
		);
});
jQuery("#add").click( function() { 
		$.ajax({
  			dataType: 'json',
  			url: 'save',
  			success: function(jsondata){
    			$("#loadImg").hide();
				$(location).attr('href', '/requests');		
  			}
		});
		$("#loadImg").show();
});
function validReq (value, id) { 
	var req = ["1","3","7","9","12","14","15", "16"];
	var a = req.indexOf(id);
	if((a>=0) && (value.length == 0)){
    	return [false, "Not Empty"]; 
	}else{    	
		return [true, ""];  
	}
}

JS;
$this->inlineScript()->captureEnd();
?>