<?php echo $this->headTitle($this->translate('Requests')); ?>
	<div id="content">
		<table id="requestlist_n"><tr><td></td></tr></table>
		<div id="prequestlist_n"></div>

		<div id="gridWrapper">
			<table id="requestlist"><tr><td></td></tr></table>
			<div id="prequestlist"></div>

			<table id="requestlist_d"><tr><td></td></tr></table>
			<div id="prequestlist_d"></div>
		</div>
	</div>
<?php
$this->inlineScript()->captureStart();
echo <<<JS
   $(function () {
		var lastSel;
	  	$("#requestlist_n").jqGrid({
			regional : 'ru',
	  		url: "requests/getrequestnumber",
	  		datatype: "json",
	  		colNames:['ID','№Сертиф.', 'Дата', '№Бланка', 'Файл', 'Статус', 'Исполнитель', 'Должность Исполнителя', 'Телефон Исполн','Email Исполн', 'Действия'],
	  		colModel:[ {name:'id',index:'id', width:'2%', search:false, hidden:true},
	  		           {name:'workorder',index:'workorder', width:'14%', searchoptions:{sopt:['eq']}},
	  		           {name:'dateorder',index:'dateorder', width:'7%',
							  searchoptions:{
							                 sopt:['eq'],
									         dataInit: function(el) {
									         setTimeout(function() {
										     $(el).datepicker({dateFormat:"dd/mm/yy"}); }, 200);
							}},
					   },
	  		           {name:'numblank',index:'numblank', width:'11%', searchoptions:{sopt:['eq']}},
                       {name:'file', index:'file', width:'14%', editable:false},
	  		           {name:'status',index:'status', width:'10%', stype: 'select',
						editoptions: {dataUrl: 'dmnrequest/getstatus',
									  style: "width:98%",
									  buildSelect: function(data) {
											 var response = jQuery.parseJSON(data);
                                             var s = '<select>';
                                             if (response && response.length) {
                               					for (var i = 0, l = response.length; i < l; i++) {
                                   				var ri = response[i];
                                   				s += '<option value="' + ri.id + '">' + ri.status + '</option>';
                               				 }
                           					}
                                            return s + "</select>";
                                    }},
						},
	  		           {name:'executor',index:'executor', width:'17%', search:false},
					   {name:'execposition',index:'execposition', width:'16%', search:false},
		 			   {name:'execphone',index:'execphone', width:'10%', search:false},
		 			   {name:'execemail',index:'execemail', width:'12%', search:false},
					   {name:'act',index:'act', width:'7%',sortable:false, search:false}
	  		          ],
			cmTemplate:{sortable:false},
	  		rowNum:5,
	  		rowList:[5,10,20,30],
	  		autowidth: true,
            shrinkToFit: true,
	  		height: '20%',
	  		pager: '#prequestlist_n',
	  		sortname: 'id',
	  		multiselect: false,
	  		viewrecords: true,
	  		sortorder: "desc",
			onSelectRow: function(){
      			 	var ids = jQuery("#requestlist_n").jqGrid('getGridParam','selrow');
					if(ids!=null){
						jQuery("#requestlist").jqGrid('setGridParam',{url:'requests/getrequest?id='+ids,page:1});
	  					jQuery("#requestlist").jqGrid('setCaption',"Детализированная информация по заявке №: "+ids)
	  					.trigger('reloadGrid');
						jQuery("#requestlist_d").jqGrid('setGridParam',{url:'requests/getrequestdesc?id='+ids,page:1});
	  					jQuery("#requestlist_d").jqGrid('setCaption',"Дополнительная информация по заявке №: "+ids)
	  					.trigger('reloadGrid');
					}else{
	  				  	ids=0;
	  				  	if($("#requestlist").jqGrid('getGridParam','records') >0 ) {
	  				  		jQuery("#requestlist").jqGrid('setGridParam',{url:'requests/getrequest?id='+ids,page:1});
	  				  		jQuery("#requestlist").jqGrid('setCaption',"Детализированная информация по заявке №: "+ids)
	  				  		.trigger('reloadGrid');
	  				  	}
						if($("#requestlist_d").jqGrid('getGridParam','records') >0 ) {
	  						jQuery("#requestlist_d").jqGrid('setGridParam',{url:'requests/getrequestdesc?id='+ids,page:1});
	  						jQuery("#requestlist_d").jqGrid('setCaption',"Дополнительная информация по заявке №: "+ids)
	  						.trigger('reloadGrid');
	  					}
	  				 }
   			},
			gridComplete: function(){
			var ids = jQuery("#requestlist_n").jqGrid('getDataIDs');
			for(var i=0;i < ids.length;i++){
				var cl = ids[i];
				xls = "<a href=\"#\"  onclick=\"xlsDownload('requests/downloadxls?id="+cl+"')\"><img src=\"images/excel.png\" title=\"Выгрузить в xls\"/></a>";
				lifecycle = "<a href=\"#\"  onclick=\"ShowLife('requests/getlifecycle?id="+cl+"')\"><img src=\"images/lifecycle.png\" title=\"Жизненный цикл заявки\"/></a>";
				jQuery("#requestlist_n").jqGrid('setRowData',ids[i],{act:xls+lifecycle});
			 }
			},
	  		caption: "Заявки заказчика"
	  	});
	  	$("#requestlist_n").jqGrid('navGrid',"#prequestlist_n", {edit:false,add:false,del:false, search:true},
		{},{},{},
		{
				closeOnEscape:true,
				multipleSearch:true,
				closeAfterSearch:true,
		}
		);
	  	$("#requestlist").jqGrid({
			regional : 'ru',
	  		url:'requests/getrequest?id=0',
	  		datatype: "json",
	  		colNames:['Наименование','Значение', 'IdReq'],
	  		colModel:[
	  		           {name:'name',index:'name', editable:false, sortable:false, width:'40%'},
	  		           {name:'value',index:'value', editable:true, editrules:{custom: true,
																			  custom_func: function (value) {
            																	return validReq(value,  jQuery("#requestlist").jqGrid('getGridParam','selrow'));
        																	 }
																		 	},
						edittype:"text", sortable:false, width:'60%'},
					   {name:'idreq',index:'idreq', hidden: true , editable: true,  editoptions: { dataInit: function(element) { $(element).attr("readonly", "readonly"); } }}
	  		         ],
			cmTemplate:{sortable:false},
	  		rowNum:15,
	  		pager: '#prequestlist',
	  		sortname: 'item',
	  		autowidth: true,
            shrinkToFit: true,
	  		height: '100%',
	  		viewrecords: true,
	  		sortorder: "asc",
	  		multiselect: false,
			onSelectRow: function(id){
      			if(id && id!==lastSel){
					jQuery('#requestlist').jqGrid('restoreRow',lastSel);
         			lastSel=id;
      			}
				jQuery('#requestlist').jqGrid('editRow',id,true);
   			},
			editurl: "request/editrequest",
	  		caption:"Детализация заявки",
	  		gridComplete: function() {
	  			var recs = parseInt($("#requestlist").getGridParam("records"),10);
	  	        if (isNaN(recs) || recs == 0) {
	  	            $("#gridWrapper").hide();
	  	        }
	  	        else {
	  	            $('#gridWrapper').show();
	  	        }
	        }
	  	});
	  	$("#requestlist").jqGrid('navGrid',"#prequestlist", {edit:false,add:false,del:false, search:false},
		{
            jqModal:true,
            savekey: [true,13],
            navkeys: [true,38,40],
            width: '50%',
            reloadAfterSubmit:true,
			closeAfterEdit:true,
			beforeShowForm: function (form) {
				var dlgDiv = $("#editmodrequestlist");
        		var parentDiv = dlgDiv.parent();
        		var dlgWidth = dlgDiv.width();
        		var parentWidth = parentDiv.width();
        		var dlgHeight = dlgDiv.height();
        		var parentHeight = parentDiv.height();
		        var parentTop = parentDiv.offset().top;
        		var parentLeft = parentDiv.offset().left;
        		dlgDiv[0].style.top =  Math.round(  parentTop  + (parentHeight-dlgHeight)/2  ) + "px";
        		dlgDiv[0].style.left = Math.round(  parentLeft + (parentWidth-dlgWidth  )/2 )  + "px";
		  }
        },
        {   jqModal:true,
            reloadAfterSubmit:true,
			closeAfterEdit:true,
			width: '50%',
			beforeShowForm: function (form) {
				var dlgDiv = $("#editmodrequestlist");
        		var parentDiv = dlgDiv.parent();
        		var dlgWidth = dlgDiv.width();
        		var parentWidth = parentDiv.width();
        		var dlgHeight = dlgDiv.height();
        		var parentHeight = parentDiv.height();
		        var parentTop = parentDiv.offset().top;
        		var parentLeft = parentDiv.offset().left;
        		dlgDiv[0].style.top =  Math.round(  parentTop  + (parentHeight-dlgHeight)/2  ) + "px";
        		dlgDiv[0].style.left = Math.round(  parentLeft + (parentWidth-dlgWidth  )/2 )  + "px";
		  }
        });
		$("#requestlist_d").jqGrid({
			regional : 'ru',
	  		url:'requests/getrequestdesc?id=0',
	  		datatype: "json",
	  		colNames:['Id','П/н №', 'К-во мест и вид упак.', 'Описание товара','Критерий', 'Кол-во товара', 'Ед.изм.', 'Номер и дата счета-фактуры'],
	  		colModel:[ {name:'id',index:'id', width:'2%', hidden: true},
	  		           {name:'paragraph',index:'paragraph', width:'5%', editable:true},
	  		           {name:'seats',index:'seats', width:'20%', editable:true},
	  		           {name:'description',index:'description', width:'32%', editable:true, edittype:"textarea", editoptions:{rows:"3",cols:"30"}},
	  		           {name:'hscode',index:'hscode', width:'6%', editable:true},
	  		           {name:'quantity',index:'quantity', width:'15%', editable:true},
	  		           {name:'unit',index:'unit', width:'10%', editable:true},
	  		           {name:'invoce',index:'invoce', width:'10%', editable:true}
	  		         ],
			cmTemplate:{sortable:false},
	  		rowNum:15,
	  		autowidth: true,
            shrinkToFit: true,
	  		height: '100%',
	  		rowList:[10,20,30],
	  		pager: '#prequestlist_d',
	  		sortname: 'item',
	  		viewrecords: true,
	  		sortorder: "asc",
	  		multiselect: false,
			editurl: "request/editrequestdesc"
	  	});
	  	$("#requestlist_d").jqGrid('navGrid','#prequestlist_d',{add:false,edit:false,del:false, search:false},
		 {
            jqModal:true,
            savekey: [true,13],
            navkeys: [true,38,40],
            width: '50%',
            reloadAfterSubmit:true,
			closeAfterEdit:true,
			beforeShowForm: function (form) {
				var dlgDiv = $("#editmodrequestlist_d");
        		var parentDiv = dlgDiv.parent();
        		var dlgWidth = dlgDiv.width();
        		var parentWidth = parentDiv.width();
        		var dlgHeight = dlgDiv.height();
        		var parentHeight = parentDiv.height();
		        var parentTop = parentDiv.offset().top;
        		var parentLeft = parentDiv.offset().left;
        		dlgDiv[0].style.top =  Math.round(  parentTop  + (parentHeight-dlgHeight)/2  ) + "px";
        		dlgDiv[0].style.left = Math.round(  parentLeft + (parentWidth-dlgWidth  )/2 )  + "px";
		  }
        },
        {   jqModal:true,
            reloadAfterSubmit:true,
			closeAfterEdit:true,
			width: '50%',
			beforeShowForm: function (form) {
				var dlgDiv = $("#editmodrequestlist_d");
        		var parentDiv = dlgDiv.parent();
        		var dlgWidth = dlgDiv.width();
        		var parentWidth = parentDiv.width();
        		var dlgHeight = dlgDiv.height();
        		var parentHeight = parentDiv.height();
		        var parentTop = parentDiv.offset().top;
        		var parentLeft = parentDiv.offset().left;
        		dlgDiv[0].style.top =  Math.round(  parentTop  + (parentHeight-dlgHeight)/2  ) + "px";
        		dlgDiv[0].style.left = Math.round(  parentLeft + (parentWidth-dlgWidth  )/2 )  + "px";
		  }
        });
});
function xlsDownload(urls)
{
  $.ajax({
				url: urls,
                cache: false,
                dataType: 'text',
                success: function(response){
                    $("#loadImg").hide();
					window.open(urls);
                }
            });
  $("#loadImg").show();
}
function validReq (value, id) {
	var req = ["0","2","6","8","11","14"];
	var a = req.indexOf(id);
	if((a>=0) && (value.length == 0)){
    	return [false, "Значение не может быть пустым"];
	}else{
		return [true, ""];
	}
}
function ShowLife(urls){
    $("#winpopup").dialog({
            	             show: { effect: "blind", duration: 800 },
							 position:{ my: "center", at: "center", of: window },
							 draggable:true,
            				 modal: true,
            				 autoOpen: false,
           					 height:200,
            				 width:300,
            				 resizable: false,
            				 title:'Жизненный цикл заявки',
        		  });
        		 $("#winpopup").load(urls);
        		 $("#winpopup").dialog("open");
        		 return false;
  };
JS;
$this->inlineScript()->captureEnd();
?>