<?php echo $this->headTitle('Ошибка 404');  ?>  
<div class="error">
<div class="comingcontainer">
    <div class="checkbacksoon">
        <p>
            <span class="go3d">4</span>
            <span class="go3d">0</span>
            <span class="go3d">4</span>
            <span class="go3d">!</span>
            
        </p>
        
        <p class="error">
        Похоже, вы выбрали неправильный путь.<br> Перейдите на главную страницу<br> </p>
             
    
    </div>
</div> 
</div>