<?php echo $this->headTitle('Акты экспериз');
$this->inlineScript()
    ->offsetSetFile(101, $this->basePath('/js/dmn/index4.js'));
?>
<div id="act" class="content">
    <table id="actlist">
        <tr>
            <td></td>
        </tr>
    </table>
    <div id="pactlist"></div>
    <div id="gridWrapper">
        <table id="acts_d">
            <tr>
                <td></td>
            </tr>
        </table>
        <div id="pacts_d"></div>
    </div>
</div>