<?= $this->headTitle($this->translate('Content')); ?>
<ol class="breadcrumb">
    <li class="breadcrumb-item active"><?= $this->translate('Content') ?></li>
</ol>
<div id="content" class="container">
    <div class="row">
        <div class="alert alert-success" role="alert">
            <h2><?= $this->translate('edit content') ?></h2>
        </div>
        <div class="margin-bottom-10">
            <button type="button" class="btn btn-info">
                <a href="<?= $this->url('dmncontent', array('action' => 'add')); ?>">
                    <i class="fa fa-plus-square-o" aria-hidden="true"></i>
                    <?= $this->translate('add content') ?></a></button>
        </div>
        <table class="table table-striped">
            <thead>
            <tr class="btn-warning">
                <th class="col-md-1 col-xs-12"><?= $this->translate('id') ?></th>
                <th class="col-md-2 col-xs-12"><?= $this->translate('alias') ?></th>
                <th class="col-md-9 col-xs-12"><?= $this->translate('title') ?></th>
                <th class="col-md-1 col-xs-12"><?= $this->translate('action') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php
            if ((isset($paginator)) && ($paginator->getCurrentItemCount() != 0)) {
                foreach ($this->paginator as $page) { ?>
                    <tr>
                        <td><?= $page['id'] ?></td>
                        <td><?= $page['static'] ?></td>
                        <td><?= $page['title'] ?></td>
                        <td><a href="dmncontent/edit?id=<?=$page['id']?>" class="btn btn-danger btn-sm"  >
                                <i class="fa fa-edit" title="<?= $this->translate('edit content') ?>" aria-hidden="true"></i></a></td>
                    </tr>
                <?php }
            } ?>
            </tbody>
        </table>
        <?php
        if ((isset($paginator)) && ($paginator->getCurrentItemCount() != 0)) {
            echo $this->paginationControl($this->paginator, 'Elastic', 'paginator-elastic', [
                'route' => 'dmncontent',
                'params' => array('action' => 'index')
            ]);
        }
        ?>
    </div>
</div>
