<?php echo $this->headTitle($this->translate('Requests'));
$this->inlineScript()
	->offsetSetFile(101, $this->basePath('/js/dmn/archive2.js'));
?>
<div id="content">
	<table id="requestlist_n">
		<tr>
			<td></td>
		</tr>
	</table>
	<div id="prequestlist_n"></div>

	<div id="gridWrapper">
		<table id="requestlist">
			<tr>
				<td></td>
			</tr>
		</table>
		<div id="prequestlist"></div>

		<table id="requestlist_d">
			<tr>
				<td></td>
			</tr>
		</table>
		<div id="prequestlist_d"></div>
	</div>
</div>
