<?php echo $this->headTitle($this->translate('Requests')); ?>
<div id="content">
<table id="requestlist_n"><tr><td></td></tr></table>
<div id="prequestlist_n"></div> 

<div id="gridWrapper">
<table id="requestlist"><tr><td></td></tr></table> 
<div id="prequestlist"></div> 

<table id="requestlist_d"><tr><td></td></tr></table> 
<div id="prequestlist_d"></div>
</div>
</div>
<?php 
$this->inlineScript()->captureStart();
echo <<<JS
   $(function () {
		var lastSel, country;
		$.getJSON("dmnrequest/getcountryjson", function(data){
		    country=data;
		});
	  	$("#requestlist_n").jqGrid({
			regional : 'ru',
	  		url: "dmnexrequest/getrequestnumber",	  		
	  		datatype: "json", 
	  		colNames:['ID','№Сертиф.', 'Дата', '№Бланка', 'Форма', 'Файл', 'Статус', 'КолДопЛист', 'Клиент', 'Должность', 'Телефон', 'Организация', 'Исполнитель', 'СтранаНазн', 'Действия'], 
	  		colModel:[ {name:'id',index:'id', width:'2%', search:false}, 
	  		           {name:'workorder',index:'workorder', width:'8%', editable:true, searchoptions:{sopt:['eq']}}, 					   
	  		           {name:'dateorder',index:'dateorder', width:'7%', editable:true, editrules: {required:true},
						editoptions: {dataInit: function(el) { 
									  setTimeout(function() { 
									  $(el).datepicker({dateFormat:"dd/mm/yy"}); }, 200); 
						}}, 
						searchoptions:{sopt:['eq'],
									   dataInit: function(el) { 
									   setTimeout(function() { 
										$(el).datepicker({dateFormat:"dd/mm/yy"}); }, 200);
						}}
					   }, 
	  		           {name:'numblank',index:'numblank', width:'7%', editable:true, searchoptions:{sopt:['eq']}},
                       {name:'forms',index:'forms', width:'6%', editable:true,  edittype: 'select', editrules: {required:true},
                        editoptions: {dataUrl: 'dmnexrequest/getforms',
									  style: "width:98%",
									  buildSelect: function(data) {
											 var response = jQuery.parseJSON(data);                                             
                                             var s = '<select>';
                                             if (response && response.length) {
                               					for (var i = 0, l = response.length; i < l; i++) {
                                   				var ri = response[i];
                                   				s += '<option value="' + ri.id + '">' + ri.forms + '</option>';
                               				 }
                           					}
                                            return s + "</select>";
                                    }}, 
                        stype: 'select',
                        searchoptions: {dataUrl: 'dmnexrequest/getforms',
									  style: "width:98%",
									  buildSelect: function(data) {
											 var response = jQuery.parseJSON(data);                                             
                                             var s = '<select>';
                                             if (response && response.length) {
                               					for (var i = 0, l = response.length; i < l; i++) {
                                   				var ri = response[i];
                                   				s += '<option value="' + ri.id + '">' + ri.forms + '</option>';
                               				 }
                           					}
                                            return s + "</select>";
                                    }}, 
                        },
                       {name:'file', index:'file', width:'5%', editable:false}, 	  		           
	  		           {name:'status',index:'status', width:'6%',editable:true, edittype: 'select', stype: 'select', editrules: {required:true},
						editoptions: {dataUrl: 'dmnexrequest/getstatus',
									  style: "width:98%",
									  buildSelect: function(data) {
											 var response = jQuery.parseJSON(data);                                             
                                             var s = '<select>';
                                             if (response && response.length) {
                               					for (var i = 0, l = response.length; i < l; i++) {
                                   				var ri = response[i];
                                   				s += '<option value="' + ri.id + '">' + ri.status + '</option>';
                               				 }
                           					}
                                            return s + "</select>";
                                    }}, 
						searchoptions:{sopt:['eq'],
									   dataUrl: 'dmnexrequest/getstatus',
									   style: "width:98%",
									   buildSelect: function(data) {
											 var response = jQuery.parseJSON(data);                                             
                                             var s = '<select>';
                                             if (response && response.length) {
                               					for (var i = 0, l = response.length; i < l; i++) {
                                   				var ri = response[i];
                                   				s += '<option value="' + ri.id + '">' + ri.status + '</option>';
                               				 }
                           					}
                                            return s + "</select>";
                                    }}
					   },
                       {name:'numdoplist', index:'numdoplist', width:'5%', editable:true, search:false},
					   {name:'name',index:'name', width:'6%', editable:false},
	  		           {name:'position',index:'position', width:'5%',editable:false, searchoptions:{sopt:['eq']}},  
					   {name:'phone',index:'phone', width:'5%',editable:false}, 
	  		           {name:'organization',index:'organization', width:'15%', editable:false, searchoptions:{sopt:['eq']}},
	  		           {name:'executor',index:'executor', width:'10%', sortable:false, editable:false},
					   {name:'destinationiso',index:'destinationiso', width:'7%',editable:true, editrules: {required:true},
                        formatter: function (cellValue) {
                                    var value = "";
                                    if(cellValue) {
                                          if (!$.isEmptyObject(country)) {
                                             value = country[cellValue];

                                          } else if(cellValue==1) {
													return "Российская Федерация";
										  } else if(cellValue==21){
													return "Республика Беларусь";
										  } else{
                                                	$.ajax({
                                                   		dataType: 'json',
                                                   		url: "dmnrequest/getcountrybyid?id="+cellValue,
                                                   		async: false,
                                                   		success: (function(result) {
                                                        	var cObject = result[0];
                                                        	value=cObject.nameru;})
                                                 	});
										   }
                                     }
                                     return value;
                        }, 
                        unformat: function (cellValue) {
                                            var value = 1;
                                                if(cellValue) {
                                                $.ajax({
                                                   dataType: 'json',
                                                   url: "dmnexrequest/getcountrybyname?rows="+cellValue,
                                                   async: false,
                                                   success: (function(result) { 
                                                        var cObject = result[0];                                                       
                                                        value = cObject.id;
                                                    })
                                                });        
                                               }
                                            return value;

                        },
                        edittype: 'select', stype: 'select',
						editoptions: {dataUrl: 'dmnexrequest/geteditcountries',
									  style: "width:98%",
									  buildSelect: function(data) {
											 var response = jQuery.parseJSON(data);                                             
                                             var s = '<select>';
                                             if (response && response.length) {
                               					for (var i = 0, l = response.length; i < l; i++) {
                                   				var ri = response[i];
                                   				s += '<option value="' + ri.id + '">' + ri.nameru + '</option>';
                               				 }
                           					}
                                            return s + "</select>";
                                    }}, 
						searchoptions:{sopt:['eq'],
									   dataUrl: 'dmnexrequest/geteditcountries',
									   style: "width:98%",
									   buildSelect: function(data) {
											 var response = jQuery.parseJSON(data);                                             
                                             var s = '<select>';
                                             if (response && response.length) {
                               					for (var i = 0, l = response.length; i < l; i++) {
                                   				var ri = response[i];
                                   				s += '<option value="' + ri.id + '">' + ri.nameru + '</option>';
                               				 }
                           					}
                                            return s + "</select>";
                                    }}
					   }, 
						{name:'act',index:'act', width:'7%',sortable:false, search:false}  
	  		          ], 
			cmTemplate:{sortable:false}, 
	  		rowNum:5, 
	  		rowList:[5,10,20,30],
	  		cellEdit:true,
			cellsubmit : "remote",
	        cellurl : "dmnexrequest/editrequestnumber",
	        afterSaveCell: function(rowid,name,val,iRow,iCol) {
	  		    if(name.localeCompare("status")==0 && val==4){
                    var isSentEmail = confirm("Вы изменили статус на действует. Отправить email заказчику?")
                    if(isSentEmail && !isNaN(rowid)){
                        $.ajax({
                        url:'dmnexrequest/sendmail?id='+rowid,
                        data: ({_search : true, filters:JSON.stringify({'groupOp':'AND','rules':[{'field':'id','op':'eq','data':rowid}]})}),
                        dataType: 'json',
                        successes: function(data){
                           Message.success('Письмо успешно отправлено заказчику');
                        }
                        });
                    } else {
                        return false;
                    }
                }
            },
            caption: "Заявки",
	  		autowidth: true,
            shrinkToFit: true, 
	  		height: '20%',
	  		pager: '#prequestlist_n',
	  		sortname: 'id', 
	  		multiselect: false,
	  		viewrecords: true, 
	  		sortorder: "desc",
			onSelectRow: function(){ 
      			 	var ids = jQuery("#requestlist_n").jqGrid('getGridParam','selrow');	
					if(ids!=null){
						jQuery("#requestlist").jqGrid('setGridParam',{url:'dmnexrequest/getrequest?id='+ids,page:1}); 
	  					jQuery("#requestlist").jqGrid('setCaption',"Деталицация заявки №: "+ids) 
	  					.trigger('reloadGrid');
						jQuery("#requestlist_d").jqGrid('setGridParam',{url:'dmnexrequest/getrequestdesc?id='+ids,page:1}); 
	  					jQuery("#requestlist_d").jqGrid('setCaption',"Дополнительная информация по заявке №: "+ids) 
	  					.trigger('reloadGrid'); 
					}else{	  				
	  				  	ids=0; 
	  				  	if($("#requestlist").jqGrid('getGridParam','records') >0 ) { 	  					
	  				  		jQuery("#requestlist").jqGrid('setGridParam',{url:'dmnexrequest/getrequest?id='+ids,page:1}); 
	  				  		jQuery("#requestlist").jqGrid('setCaption',"Деталицация заявки №: "+ids) 
	  				  		.trigger('reloadGrid'); 
	  				  	}
						if($("#requestlist_d").jqGrid('getGridParam','records') >0 ) { 
	  						jQuery("#requestlist_d").jqGrid('setGridParam',{url:'dmnexrequest/getrequestdesc?id='+ids,page:1}); 
	  						jQuery("#requestlist_d").jqGrid('setCaption',"Дополнительная информация по заявке №: "+ids) 
	  						.trigger('reloadGrid'); 
	  					} 
	  				 }    			
   			}, 
			gridComplete: function(){
			var ids = jQuery("#requestlist_n").jqGrid('getDataIDs');
			for(var i=0;i < ids.length;i++){
				var cl = ids[i];
				xls = "<a href=\"#\"  onclick=\"DownloadXls('dmnexrequest/downloadxls?id="+cl+"')\"><img src=\"images/excel.png\" title=\"Выгрузить в xls\"/></a>"; 
				xml = "<a href=\"#\"  onclick=\"DownloadXml('dmnexrequest/downloadxml?id="+cl+"')\"><img src=\"images/xml.png\" title=\"Выгрузить в xml\"/></a>";
				print = "<a href=\"#\"  onclick=\"DownloadPrint('dmnexrequest/downloadprint?id="+cl+"')\"><img src=\"images/PrintPreview.png\" title=\"Выгрузить для печати\"/></a>";
	    		lifecycle = "<a href=\"#\"  onclick=\"ShowLife('dmnexrequest/getlifecycle?id="+cl+"')\"><img src=\"images/lifecycle.png\" title=\"Жизненный цикл заявки\"/></a>";
				jQuery("#requestlist_n").jqGrid('setRowData',ids[i],{act:xls+xml+print+lifecycle});
			 }
			}, 
	  		/*editurl: "dmnexrequest/editrequestnumber",	  */

	  	});		  	
	  	$("#requestlist_n").jqGrid('navGrid',"#prequestlist_n", {edit:false,add:false,del:false, search:true},
		 {   
            jqModal:true,
            savekey: [true,13], 
            navkeys: [true,38,40],
            width: '50%',  
            reloadAfterSubmit:true,
			closeAfterEdit:true, 
			beforeShowForm: function (form) {				
				var dlgDiv = $("#editmodrequestlist_n");
        		var parentDiv = dlgDiv.parent(); 
        		var dlgWidth = dlgDiv.width();
        		var parentWidth = parentDiv.width();
        		var dlgHeight = dlgDiv.height();
        		var parentHeight = parentDiv.height();
		        var parentTop = parentDiv.offset().top;
        		var parentLeft = parentDiv.offset().left;
        		dlgDiv[0].style.top =  Math.round(  parentTop  + (parentHeight-dlgHeight)/2  ) + "px";
        		dlgDiv[0].style.left = Math.round(  parentLeft + (parentWidth-dlgWidth  )/2 )  + "px";
		  }
        }, 
        {   jqModal:true,
            reloadAfterSubmit:true,
			closeAfterEdit:true, 
			width: '50%',
			beforeShowForm: function (form) {				
				var dlgDiv = $("#editmodrequestlist_n");
        		var parentDiv = dlgDiv.parent(); 
        		var dlgWidth = dlgDiv.width();
        		var parentWidth = parentDiv.width();
        		var dlgHeight = dlgDiv.height();
        		var parentHeight = parentDiv.height();
		        var parentTop = parentDiv.offset().top;
        		var parentLeft = parentDiv.offset().left;
        		dlgDiv[0].style.top =  Math.round(  parentTop  + (parentHeight-dlgHeight)/2  ) + "px";
        		dlgDiv[0].style.left = Math.round(  parentLeft + (parentWidth-dlgWidth  )/2 )  + "px";
		 },		 
        },
		{},
		{		closeOnEscape:true, 
				multipleSearch:true, 
				closeAfterSearch:true,
		 }		
		);					  	
	  	$("#requestlist").jqGrid({
			regional : 'ru', 	  		
	  		url:'dmnexrequest/getrequest?id=0', 
	  		datatype: "json", 
	  		colNames:['Наименование','Значение', 'IdReq'], 
	  		colModel:[ 
	  		           {name:'name',index:'name', editable:false, sortable:false, width:'40%'}, 
	  		           {name:'value',index:'value', editable:true, editrules:{custom: true, 
																			  custom_func: function (value) {
            																	return validReq(value,  jQuery("#requestlist").jqGrid('getGridParam','selrow'));
        																	 }
																		 	}, 
						edittype:"text", sortable:false, width:'60%'}, 	
					   {name:'idreq',index:'idreq', hidden: true , editable: true,  editoptions: { dataInit: function(element) { $(element).attr("readonly", "readonly"); } }} 		           
	  		         ], 
	  		rowNum:15,			
			cmTemplate:{sortable:false},  		
	  		pager: '#prequestlist', 
	  		sortname: 'item', 
	  		autowidth: true,
            shrinkToFit: true, 
	  		height: '100%',
	  		viewrecords: true, 
	  		sortorder: "asc", 
	  		multiselect: false,
			onSelectRow: function(id){ 
      			if(id && id!==lastSel){ 
					jQuery('#requestlist').jqGrid('restoreRow',lastSel);         			
         			lastSel=id; 
      			} 
				jQuery('#requestlist').jqGrid('editRow',id,true);      			
   			}, 
			editurl: "dmnexrequest/editrequest",
	  		caption:"Детализация заявки",
	  		gridComplete: function() {
	  			var recs = parseInt($("#requestlist").getGridParam("records"),10);
	  	        if (isNaN(recs) || recs == 0) {
	  	            $("#gridWrapper").hide();
	  	        }
	  	        else {
	  	            $('#gridWrapper').show();	  	            
	  	        }
	        }
	  	});	  	
	  	$("#requestlist").jqGrid('navGrid',"#prequestlist", {edit:false,add:false,del:false, search:false},
		{   
            jqModal:true,
            savekey: [true,13], 
            navkeys: [true,38,40],
            width: '50%',   
            reloadAfterSubmit:true,
			closeAfterEdit:true,
			beforeShowForm: function (form) {				
				var dlgDiv = $("#editmodrequestlist");
        		var parentDiv = dlgDiv.parent(); 
        		var dlgWidth = dlgDiv.width();
        		var parentWidth = parentDiv.width();
        		var dlgHeight = dlgDiv.height();
        		var parentHeight = parentDiv.height();
		        var parentTop = parentDiv.offset().top;
        		var parentLeft = parentDiv.offset().left;
        		dlgDiv[0].style.top =  Math.round(  parentTop  + (parentHeight-dlgHeight)/2  ) + "px";
        		dlgDiv[0].style.left = Math.round(  parentLeft + (parentWidth-dlgWidth  )/2 )  + "px";
		  } 
        }, 
        {   jqModal:true,
            reloadAfterSubmit:true,
			closeAfterEdit:true,
			width: '50%',
			beforeShowForm: function (form) {				
				var dlgDiv = $("#editmodrequestlist");
        		var parentDiv = dlgDiv.parent(); 
        		var dlgWidth = dlgDiv.width();
        		var parentWidth = parentDiv.width();
        		var dlgHeight = dlgDiv.height();
        		var parentHeight = parentDiv.height();
		        var parentTop = parentDiv.offset().top;
        		var parentLeft = parentDiv.offset().left;
        		dlgDiv[0].style.top =  Math.round(  parentTop  + (parentHeight-dlgHeight)/2  ) + "px";
        		dlgDiv[0].style.left = Math.round(  parentLeft + (parentWidth-dlgWidth  )/2 )  + "px";
		  } 
        });			
		$("#requestlist_d").jqGrid({
			regional : 'ru', 	  		
	  		url:'dmnexrequest/getrequestdesc?id=0', 
	  		datatype: "json", 
	  		colNames:['Id','П/н №', 'К-во мест и вид упак.', 'Описание товара','Критерий', 'Кол-во товара', 'Ед.изм.', 'Номер и дата счета-фактуры'], 
	  		colModel:[ {name:'id',index:'id', hidden: true, width:'2%'}, 
	  		           {name:'paragraph',index:'paragraph', width:'5%', editable:true}, 
	  		           {name:'seats',index:'seats', width:'20%', editable:true, edittype:"textarea", editoptions:{rows:"2",cols:"30"}}, 
	  		           {name:'description',index:'description', width:'32%', editable:true, edittype:"textarea", editoptions:{rows:"3",cols:"30"}}, 
	  		           {name:'hscode',index:'hscode', width:'6%', editable:true, edittype:"textarea", editoptions:{rows:"2",cols:"30"}}, 
	  		           {name:'quantity',index:'quantity', width:'15%', editable:true, edittype:"textarea", editoptions:{rows:"2",cols:"30"}}, 
	  		           {name:'unit',index:'unit', width:'10%', editable:true, edittype:"textarea", editoptions:{rows:"2",cols:"30"}}, 
	  		           {name:'invoce',index:'invoce', width:'10%', editable:true, edittype:"textarea", editoptions:{rows:"2",cols:"30"}}	  		           
	  		         ], 
			cmTemplate:{sortable:false}, 
	  		rowNum:15,
	  		autowidth: true,
            shrinkToFit: true, 
	  		height: '100%',
	  		rowList:[10,20,30], 
	  		pager: '#prequestlist_d', 
	  		sortname: 'item', 
	  		viewrecords: true, 
	  		sortorder: "asc", 
	  		multiselect: false, 
			editurl: "dmnexrequest/editrequestdesc",
	  		caption:"Дополнительная информация по заявке"	  		
	  	}); 
	  	$("#requestlist_d").jqGrid('navGrid','#prequestlist_d',{add:false,edit:true,del:false, search:false},
		 {   
            jqModal:true,
            savekey: [true,13], 
            navkeys: [true,38,40],
            width: '50%',  
            reloadAfterSubmit:true,
			closeAfterEdit:true,
			beforeShowForm: function (form) {				
				var dlgDiv = $("#editmodrequestlist_d");
        		var parentDiv = dlgDiv.parent(); 
        		var dlgWidth = dlgDiv.width();
        		var parentWidth = parentDiv.width();
        		var dlgHeight = dlgDiv.height();
        		var parentHeight = parentDiv.height();
		        var parentTop = parentDiv.offset().top;
        		var parentLeft = parentDiv.offset().left;
        		dlgDiv[0].style.top =  Math.round(  parentTop  + (parentHeight-dlgHeight)/2  ) + "px";
        		dlgDiv[0].style.left = Math.round(  parentLeft + (parentWidth-dlgWidth  )/2 )  + "px";
		  } 
        }, 
        {   jqModal:true,
            reloadAfterSubmit:true,
			closeAfterEdit:true, 
			width: '50%', 
			beforeShowForm: function (form) {				
				var dlgDiv = $("#editmodrequestlist_d");
        		var parentDiv = dlgDiv.parent(); 
        		var dlgWidth = dlgDiv.width();
        		var parentWidth = parentDiv.width();
        		var dlgHeight = dlgDiv.height();
        		var parentHeight = parentDiv.height();
		        var parentTop = parentDiv.offset().top;
        		var parentLeft = parentDiv.offset().left;
        		dlgDiv[0].style.top =  Math.round(  parentTop  + (parentHeight-dlgHeight)/2  ) + "px";
        		dlgDiv[0].style.left = Math.round(  parentLeft + (parentWidth-dlgWidth  )/2 )  + "px";
		  }
        });
});
function DownloadXls(urls)
{ 
  $.ajax({     
				url: urls,                
                cache: false,
                dataType: 'text',				                
                success: function(response){					
                    $("#loadImg").hide();						
					window.open(urls);
                }
            });
  $("#loadImg").show();
} 
function DownloadXml(urls)
{ 
  $.ajax({     
				url: urls,                
                cache: false,
                dataType: 'xml',				                
                success: function(response){					
                    $("#loadImg").hide();								
					if(response.getElementsByTagName("error").length==0)											
					 window.open(urls);
					else					 
					 alert($(response).find('error').text());
				  					 
                }
            });
  $("#loadImg").show();
} 
function DownloadPrint(urls)
{ 
  $.ajax({     
				url: urls,                
                cache: false,
                dataType: 'text',				                
                success: function(response){
                     $("#loadImg").hide();	
                    var error=response.substring(0, 5);	                    
                    if(response.substring(0, 5)=='error'){
                        alert(response.substring(5));
                    }else{				
					    window.open(urls);
                    }
                }
            });
  $("#loadImg").show();
} 
function validReq (value, id) { 
	var req = ["0","2","6","8","11","14"];
	var a = req.indexOf(id);
	if((a>=0) && (value.length == 0)){
    	return [false, "Значение не может быть пустым"]; 
	}else{    	
		return [true, ""];  
	}
}
function ShowLife(urls){
    $("#winpopup").dialog({
            	             show: { effect: "blind", duration: 800 },
							 position:{ my: "center", at: "center", of: window },
							 draggable:true,
            				 modal: true,
            				 autoOpen: false,
           					 height:250,
            				 width:250,
            				 resizable: false,
            				 title:'Жизненный цикл заявки',           											
        		  });
        		 $("#winpopup").load(urls);
        		 $("#winpopup").dialog("open");        
        		 return false;
  }; 
JS;
$this->inlineScript()->captureEnd();
?>