<?php echo $this->headTitle($this->translate('LifeCycle')); ?>
<div id="gridWrapper">
    <table class="table table-striped">
        <thead>
        <tr><th><?php echo $this->translate('Статус');?></th><th><?php echo $this->translate('Дата');?></th></tr>
        </thead>
        <tbody>
        <?php foreach ($data as $showId) { ?>
            <?php foreach ($showId as $key => $value) { ?>
                <?php if (strcmp($key, 'id') != 0 && !is_null($value)) { ?>
                    <tr>
                        <td><?php echo $this->translate($key); ?></td>
                        <td><?php echo $value->format('d.m.Y'); ?></td>
                    </tr>
                    <?php
                }
            }
        }
        ?>
        </tbody>
    </table>
</div>