<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" >
    <head>        
        <?php echo $this->headTitle($this->translate('УП "Могилевское отделение БелТПП"'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <!-- meta -->
        
        <?php echo $this->headMeta()->prependHttpEquiv('viewport', 'width=device-width, initial-scale=1.0') ?>
        <?php echo $this->headMeta()->prependHttpEquiv('Content-Type', 'text/html; charset=utf-8') ?>
        <?php echo $this->headMeta()->prependHttpEquiv('X-UA-Compatible', 'IE=edge') ?>

        <!-- styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))                        
                        ->prependStylesheet($this->basePath() . '/css/main.css')
                        ->prependStylesheet($this->basePath() . '/css/ui-lightness/jquery-ui.css')                       
        				->prependStylesheet($this->basePath() . '/css/ui-lightness/theme.css');
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->offsetSetFile(1, $this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        							  ->offsetSetFile(2, $this->basePath() . 'http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        							  ->offsetSetFile(3, $this->basePath() . '/js/jquery/jquery.min.js')  
        							  ->offsetSetFile(4, $this->basePath() . '/js/jquery/jquery-ui.js');
	
	   ?>
    </head>
	<body>	 
       <header>
       		<div class="Logo">
				<p class="rus">Белорусская <br /> торгово-промышленная палата <br />Могилевское отделение</p>				
				<p class="eng">Belarusian  <br />Chamber of Commerce and Industry<br />Mogilev branch</p>
			</div>
	  </header>   
	<div class="wrap">
		<div class="container">
		 <div class="main_wrap">
		 <div class="subheader"> 		 	
		 	<a href="http://cci.mogilev.by" target="_blank">Вернуться на сайт</a>
		 </div>
    		 <div class="main"> 	
        		<?php echo $this->content; ?> 
        		<?php echo $this->inlineScript() ?>     
   			 </div>
			</div>
    	</div>
    </div>     
    </body>
</html>
