<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
       aria-expanded="false"><i class="fa fa-database"
                                aria-hidden="true"></i> <?= $this->translate('Sertificates'); ?>
        <span class="caret"></span></a>
    <ul class="dropdown-menu multi-level" role="menu" aria-labelledby="dropdownMenu">
        <li class="<?=((($route == "dmnrequest") && ($action == "index")) ? "active" : "") ?>"><a
                href="<?= $this->url('dmnrequest', array('action' => 'index')); ?>" id="view"><i
                    class="fa fa-list"></i> <?= $this->translate('View'); ?></a></li>
        <li class="<?=((($route == "dmnupload") && ($action == "index")) ? "active" : "") ?>"><a
                href="<?= $this->url('dmnupload', array('action' => 'index')); ?>" id="upload" data-role="<?= $role ?>"><i
                    class="fa fa-upload"></i> <?= $this->translate('Upload'); ?></a></li>
        <li class="<?=((($route == "dmnrequest") && ($action == "add")) ? "active" : "") ?>"><a
                href="<?= $this->url('dmnrequest', array('action' => 'add')); ?>" id="addition"><i
                    class="fa fa-plus-square"></i> <?= $this->translate('Add'); ?></a></li>
        <li role="separator" class="divider"></li>
        <li class="dropdown-submenu">
            <a tabindex="-1" href="#">
                <i class="fa fa-calendar" aria-hidden="true"></i> <?= $this->translate('Archive'); ?>
            </a>
            <ul class="dropdown-menu">
                <li class="<?=((($route == "dmnrequest") && ($action == "archive")) ? "active" : "") ?>"><a
                        href="<?= $this->url('dmnrequest', array('action' => 'archive')); ?>"
                        id="view"><i
                            class="fa fa-list"></i> 2015</a></li>
            </ul>
        </li>
    </ul>
</li>
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
       aria-expanded="false"><i class="fa fa-cog" aria-hidden="true"></i> <?= $this->translate('Management'); ?>
        <span class="caret"></span></a>
    <ul class="dropdown-menu multi-level" role="menu" aria-labelledby="dropdownMenu">
        <li class="<?=((($route == "dmnuser") && ($action == "index")) ? "active" : "") ?>"><a
                href="<?= $this->url('dmnuser', array('action' => 'index')); ?>" id="users"><i
                    class="fa fa-users"></i> <?= $this->translate('Clients'); ?></a></li>
        <li class="<?=((($route == "dmnexecutor") && ($action == "index")) ? "active" : "") ?>"><a
                href="<?= $this->url('dmnexecutor', array('action' => 'index')); ?>" id="executors"><i
                    class="fa fa-graduation-cap"></i> <?= $this->translate('Executors'); ?></a></li>
        <li class="<?=((($route == "dmncontent") && ($action == "index")) ? "active" : "") ?>"><a
                href="<?= $this->url('dmncontent', array('action' => 'index')); ?>" id="edcontent"><i
                    class="fa fa-pencil-square-o"></i> <?= $this->translate('Content'); ?></a></li>
    </ul>
</li>
<li class="<?=((($route == "dmnstatistics") && ($action == "index")) ? "active" : "") ?>"><a
        href="<?= $this->url('dmnstatistics', array('action' => 'index')); ?>" id="statistics"><i
            class="fa fa-pie-chart" aria-hidden="true"></i> <?= $this->translate('Statistics'); ?></a></li>
<li class="<?=((($route == "dmnact") && ($action == "index")) ? "active" : "") ?>"><a
        href="<?= $this->url('dmnact', array('action' => 'index')); ?>" id="act"><i
            class="fa fa-tasks" aria-hidden="true"></i> <?= 'Акты'; ?></a></li>