<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
       aria-expanded="false"><i class="fa fa-database"
                                aria-hidden="true"></i> <?= $this->translate('Sertificates'); ?>
        <span class="caret"></span></a>
    <ul class="dropdown-menu multi-level" role="menu" aria-labelledby="dropdownMenu">
        <li class="<?=((($route == "dmnexrequest") && ($action == "index")) ? "active" : "") ?>"><a
                href="<?= $this->url('dmnexrequest', array('action' => 'index')); ?>" id="view"><i
                    class="fa fa-list"></i> <?= $this->translate('View'); ?></a></li>
        <li class="<?=((($route == "dmnexrequest") && ($action == "upload")) ? "active" : "") ?>"><a
                href="<?= $this->url('dmnexrequest', array('action' => 'upload')); ?>" id="upload" data-role="<?= $role ?>"><i
                    class="fa fa-upload"></i> <?= $this->translate('Upload'); ?></a></li>
        <li class="<?=((($route == "dmnexrequest") && ($action == "add")) ? "active" : "") ?>"><a
                href="<?= $this->url('dmnexrequest', array('action' => 'add')); ?>" id="addition"><i
                    class="fa fa-plus-square"></i> <?= $this->translate('Add'); ?></a></li>
        <li role="separator" class="divider"></li>
        <li class="dropdown-submenu">
            <a tabindex="-1" href="#">
                <i class="fa fa-calendar" aria-hidden="true"></i> <?= $this->translate('Archive'); ?>
            </a>
            <ul class="dropdown-menu">
                <li class="<?=((($route == "dmnexrequest") && ($action == "archive")) ? "active" : "") ?>">
                    <a href="<?= $this->url('archive', array('year'=>2015)); ?>" id="view">
                        <i class="fa fa-list"></i> 2015
                    </a>
                </li>
                <li class="<?=((($route == "dmnexrequest") && ($action == "archive")) ? "active" : "") ?>">
                    <a href="<?= $this->url('archive', array('year'=>2016)); ?>" id="view">
                        <i class="fa fa-list"></i> 2016
                    </a>
                </li>
            </ul>
        </li>
    </ul>
</li>
<li class="<?=((($route == "dmnexact") && ($action == "index")) ? "active" : "") ?>"><a
        href="<?= $this->url('dmnexact', array('action' => 'index')); ?>" id="act"><i
            class="fa fa-tasks" aria-hidden="true"></i> <?= 'Акты экспертизы'; ?></a></li>
