<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <?php echo $this->headTitle($this->translate('УП "Могилевское отделение БелТПП"'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <!-- meta -->
    <?php echo $this->headMeta()->prependHttpEquiv('viewport', 'width=device-width, initial-scale=1.0') ?>
    <?php echo $this->headMeta()->prependHttpEquiv('Content-Type', 'text/html; charset=utf-8') ?>
    <?php echo $this->headMeta()->prependHttpEquiv('X-UA-Compatible', 'IE=edge') ?>

    <!-- styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
        ->offsetSetStylesheet(1, $this->basePath() . '/components/bootstrap/dist/css/bootstrap.min.css')
        ->offsetSetStylesheet(2, $this->basePath() . '/components/components-font-awesome/css/font-awesome.min.css')
        ->offsetSetStylesheet(3, $this->basePath() . '/components/jGrowl/jquery.jgrowl.min.css')
        ->offsetSetStylesheet(4, $this->basePath() . '/components/jquery-ui/themes/ui-lightness/jquery-ui.min.css')
        ->offsetSetStylesheet(5, $this->basePath() . '/components/jquery-ui/themes/ui-lightness/theme.css')
        ->offsetSetStylesheet(6, $this->basePath() . '/components/jqGrid/css/ui.jqgrid.css')
        ->offsetSetStylesheet(7, $this->basePath() . '/css/style.css');
    ?>
</head>
<body id="layout">
<header>
    <section class="col-lg-10 col-lg-offset-1 col-md-12 col-sm-12 col-xs-12 brand">
        <div class="logo visible-md-block visible-lg-block visible-sm-block">
            <span class="rus">Белорусская <br/> торгово-промышленная палата <br/>Могилевское отделение</span>
            <span class="eng">Belarusian  <br/>Chamber of Commerce and Industry<br/>Mogilev branch</span>
        </div>
        <div class="logo-xs visible-xs-block">
            <span class="rus">Белорусская торгово-промышленная палата Могилевское отделение</span>
            <span class="eng">Belarusian Chamber of Commerce and Industry Mogilev branch</span>
        </div>
    </section>
</header>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Меню</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <?php
                if ((isset($auth) && is_array($auth)) && (isset($active) && is_array($active))) {
                    foreach ($auth as $key => $value) {
                        if ($value instanceof \DmnDatabase\Entity\CciBjyRole) {
                            $role = $value->getId();
                        } else {
                            $role = 1;
                        }
                    }
                    $route = $active['route'];
                    $action = $active['action'];
                    switch ($role) {
                        case '2':
                            echo $this->partial('header2', array('route' => $route, 'action' => $action));
                            break;
                        case '3':
                            echo $this->partial('header3', array('route' => $route, 'action' => $action));
                            break;
                        case '4':
                            echo $this->partial('header4', array('route' => $route, 'action' => $action));
                            break;
                        case '5':
                            echo $this->partial('header5', array('route' => $route, 'action' => $action));
                            break;
                    }
                } ?>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <?php if (isset($identity) && ($identity instanceof \Zend\Authentication\AuthenticationService)
                    && ($identity->getIdentity() instanceof \DmnDatabase\Entity\CciZfUser)
                ) { ?>
                    <li><a href="#"><?php echo $identity->getIdentity()->getDisplayName(); ?></a></li>
                <?php } ?>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">Панель управления <i class="fa fa-ellipsis-v"></i> <span
                            class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <?php if ((($route == "dmnrequest") && ($action == "index")) || (($route == "dmnexrequest") && ($action == "index")) || (($route == "requests") && ($action == "index"))) { ?>
                            <li><a href="#" id="helpHref"
                                   data-href="<?php echo $this->url('application', array('action' => 'help', 'id' => '2')); ?>"><i
                                        class="fa fa-info"></i> Помощь</a>
                            </li>
                        <?php } elseif ((($route == "dmnupload") && ($action == "index")) || (($route == "requests") && ($action == "upload")) || (($route == "dmnexrequest") && ($action == "upload"))) { ?>
                            <li><a href="#" id="helpHref"
                                   data-href="<?php echo $this->url('application', array('action' => 'help', 'id' => '4')); ?>"><i
                                        class="fa fa-info"></i> Помощь</a>
                            </li>
                        <?php } elseif ((($route == "dmnrequest") && ($action == "add")) || (($route == "requests") && ($action == "add")) || (($route == "dmnexrequest") && ($action == "add"))) { ?>
                            <li><a href="#" id="helpHref"
                                   data-href="<?php echo $this->url('application', array('action' => 'help', 'id' => '3')); ?>"><i
                                        class="fa fa-info"></i> Помощь</a>
                            </li>
                        <?php } else { ?>
                            <li><a href="#" id="helpHref"
                                   data-href="<?php echo $this->url('application', array('action' => 'help', 'id' => '2')); ?>"><i
                                        class="fa fa-info"></i> Помощь</a>
                            </li>
                        <?php } ?>
                        <li><a href="#" id="changePass"
                               data-href="<?php echo $this->url('zfcuser/changepassword'); ?>"><i
                                    class="fa fa-info"></i> Сменить пароль</a>
                        </li>
                        <li><a href="/maketCT-1.xls"><i class="fa fa-download"></i> Скачать шаблон</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="<?php echo $this->url('zfcuser/logout'); ?>"><i class="fa fa-sign-out"></i>
                                Выйти</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>
<section class="main">
    <div class="container-fluid">
        <noscript>Ваш браузер не поддерживает Javascript. Воспользуйтесь следующими рекомендациями <a
                href="http://help.yandex.ru/common/browsers-settings/browsers-java-js-settings.xml"
                target="_blank">для включения данной функции</a> ,после чего обновите страницу.
        </noscript>
        <?php echo $this->content; ?>
        <div id="loadImg">
            <div id="img">
                <img src="<?php echo $this->basePath('/images/495.gif') ?>"/></div>
        </div>
        <div class="modal fade" id="modalHelp" tabindex="-1" role="dialog" aria-labelledby="modalHelp">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">Помощь по использованию ресурса</h4>
                    </div>
                    <div class="modal-body">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Scripts -->
<?php
echo $this->inlineScript()->offsetSetFile(1, $this->basePath('/components/jquery/dist/jquery.min.js'))
    ->offsetSetFile(2, $this->basePath('/components/jGrowl/jquery.jgrowl.min.js'))
    ->offsetSetFile(3, $this->basePath('/components/bootstrap/dist/js/bootstrap.min.js'))
    ->offsetSetFile(4, $this->basePath('/components/jquery-ui/jquery-ui.min.js'))
    ->offsetSetFile(5, $this->basePath('/components/jqGrid/js/i18n/grid.locale-ru.js'))
    ->offsetSetFile(6, $this->basePath('/components/jqGrid/js/jquery.jqGrid.min.js'))
    ->offsetSetFile(7, $this->basePath('/js/custom.js'));
?>
</body>
</html>
