<body style="background:#F6F6F6; font-family:Verdana, Arial, Helvetica, sans-serif; font-size:12px; margin:0; padding:0;">
<div style="background:#F6F6F6; font-family:Verdana, Arial, Helvetica, sans-serif; font-size:12px; margin:0; padding:0;">
<table cellspacing="0" cellpadding="0" border="0" height="100%" width="100%">
		<tr>
			<td align="center" valign="top" style="padding:20px 0 20px 0">
				<!-- [ header starts here] -->
				<table bgcolor="FFFFFF" cellspacing="0" cellpadding="10" border="0" width="650" style="border:1px solid #E0E0E0;">
					<tr>
						<td valign="top">
							<a href="parts1.ru">www.cci.mogilev.by</a>
						</td>
					</tr>
					<!-- [ middle starts here] -->
					<tr>
						<td valign="top">
							<h1 style="font-size:22px; font-weight:normal; line-height:22px; margin:0 0 11px 0;">Заявка на перевод</h1>
							<p style="font-size:12px; line-height:16px; margin:0 0 8px 0;">Данные по заявке:</p>
							<table style="border:1px solid #E0E0E0; font-size:12px; line-height:16px; margin:0 0 16px 0; padding:13px 18px; background:#f9f9f9; width:600px">								
								<tr><th colspan="2"><strong>Информация о заказчике</strong></th></tr>						
								<tr><td>Наименование Организации</td><td><?php echo $organization;?></td></tr>
								<tr><td>Контактное лицо</td><td><?php echo $contact;?></td></tr>
								<tr><td>Телефон </td><td><?php echo $phone;?> </td></tr>							
								<tr><td>Адрес электронной почты</td><td>
								    <a href="mailto:<?php echo $email;?>" style="color:#1E7EC8;"><?php echo $email;?></a>	
								</td></tr>	
								<?php if(isset($info) && !empty($info)) { ?>							
								<tr><td>Дополнительная информация </td><td><?php echo $info;?> </td></tr>	
								<?php } ?>								
								</table>
						</td>
					</tr>					
				</table>
			</td>
		</tr>
	</table>
