<?php echo $this->headTitle($this->translate('Add Request'));
$this->inlineScript()
    ->offsetSetFile(101, $this->basePath('/js/dmn/indexa1.js'));
?>
<div id="content" class="content">
    <div class="form-group">
        <table id="requestorg">
            <tr>
                <td></td>
            </tr>
        </table>
        <table id="requestlist">
            <tr>
                <td></td>
            </tr>
        </table>
        <table id="requestlist_d">
            <tr>
                <td></td>
            </tr>
        </table>
        <div id="prequestlist_d"></div>
    </div>
    <div class="form-group">
        <input type="button" id="add" class="btn btn-info addbutton" value="Отправить заявку"/>
    </div>
</div>