<?php echo $this->headTitle($this->translate('Requests'));
      $this->inlineScript()
			->offsetSetFile(101, $this->basePath('/js/dmn/admin/index1.js'))
			->offsetSetFile(102, $this->basePath('/js/dmn/admin/index2.js'))
			->offsetSetFile(103, $this->basePath('/js/dmn/admin/index3.js'));
?>
    <div id="content" class="content">
        <table id="requestlist_n">
            <tr>
                <td></td>
            </tr>
        </table>
        <div id="prequestlist_n"></div>
        <div id="gridWrapper">
            <table id="requestlist">
                <tr>
                    <td></td>
                </tr>
            </table>
            <div id="prequestlist"></div>

            <table id="requestlist_d">
                <tr>
                    <td></td>
                </tr>
            </table>
            <div id="prequestlist_d"></div>
        </div>
    </div>
    <div id="content2" class="content"></div>
    <div id="content3" class="content"></div>