<body
    style="background:#F6F6F6; font-family:Verdana, Arial, Helvetica, sans-serif; font-size:12px; margin:0; padding:0;">
<div
    style="background:#F6F6F6; font-family:Verdana, Arial, Helvetica, sans-serif; font-size:12px; margin:0; padding:0;">
    <table cellspacing="0" cellpadding="0" border="0" height="100%" width="100%">
        <tr>
            <td align="center" valign="top" style="padding:20px 0 20px 0">
                <!-- [ header starts here] -->
                <table bgcolor="FFFFFF" cellspacing="0" cellpadding="10" border="0" width="650"
                       style="border:1px solid #E0E0E0;">
                    <tr>
                        <td valign="top" style="font-size:18px; font-weight:normal; line-height:16px; margin:0 0 11px 0;">
                           <a href="https://ccimogilev.by">УП "Могилевское отделение "БелТПП"</a>
                        </td>
                    </tr>
                    <!-- [ middle starts here] -->
                    <tr>
                        <td valign="top">
                            <h3 style="font-size:16px; font-weight:normal; line-height:16px; margin:0 0 11px 0;">Ваша заявка на получение сертификата по форме: "<?php echo $forms; ?>" готова</h3>

                            <p style="font-size:12px; line-height:16px; margin:0 0 8px 0;">Данные по заявке:</p>
                            <table
                                style="border:1px solid #E0E0E0; font-size:12px; line-height:16px; margin:0 0 16px 0; padding:13px 18px; background:#f9f9f9; width:600px">
                                <tr>
                                    <td style="width:50%">Номер сертификата</td>
                                    <td style="width:50%"><?php
                                        echo $workorder;
                                        ?></td>
                                </tr>
                                <tr>
                                    <td>Организация:</td>
                                    <td><?php echo $organization; ?></td>
                                </tr>
                                <tr>
                                    <td>Исполнитель:</td>
                                    <td><?php echo $executor; ?></td>
                                </tr>
                                <tr>
                                    <td>Телефон исполнителя:</td>
                                    <td><?php echo $execphone; ?> </td>
                                </tr>
                                <tr>
                                    <td>Email исполнителя:</td>
                                    <td><?php echo $execemail; ?> </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</div>
</body>
