<div id="help" class="row">
    <div class="info">
        <?php
        if(is_null($form))
            $form = $this->changePasswordForm;
        $form->prepare();
        $form->setAttribute('action', $this->url('zfcuser/changepassword'));
        $form->setAttribute('method', 'post');
        $form->setAttribute('id', 'changePassForm');
        $form->setAttribute('role', 'form');

        $emailElement = $form->get('identity');
        $emailElement->setValue($this->zfcUserIdentity()->getEmail());

        echo $this->form()->openTag($form);?>

        <?php echo $this->formElementErrors($form->get('identity')); ?><?php echo $this->formInput($form->get('identity')); ?>
        <div class="form-group">
            <?php
            $credential = $form->get('credential');
            $credential->setAttribute('class', 'form-control');
            ?>
            <label for="credential" class="control-label"><?php echo $this->translate($credential->getLabel()); ?></label>
            <?php echo $this->formInput($credential) ?>
        </div>
        <div class="form-group">
            <?php
            $newCredential = $form->get('newCredential');
            $newCredential->setAttribute('class', 'form-control');
            ?>
            <label for="credential" class="control-label"><?php echo $this->translate($newCredential->getLabel()); ?></label>
            <?php echo $this->formInput($newCredential) ?>
        </div>
        <div class="form-group">
            <?php
            $newCredentialVerify = $form->get('newCredentialVerify');
            $newCredentialVerify->setAttribute('class', 'form-control');
            ?>
            <label for="credential" class="control-label"><?php echo $this->translate($newCredentialVerify->getLabel()); ?></label>
            <?php echo $this->formInput($newCredentialVerify) ?>
        </div>
        <div class="form-group">
        <?php
        $submit = $form->get('submit');
        $submit->setAttributes(array(
            'value' => $this->translate('Submit')));
        $submit->setAttribute('class', 'btn  btn-info addbutton');
        echo $this->formInput($submit);
        ?>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>