<div class="container-fluid">
    <div id="login-overlay" class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel"><?php echo $this->translate('Input you Email And Password'); ?></h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-xs-6">
                        <div class="well">
                            <?php
                            $form = $this->loginForm;
                            $form->prepare();
                            $form->setAttribute('action', $this->url('home'));
                            $form->setAttribute('method', 'post');
                            $form->setAttribute('id', 'loginForm');
                            $form->setAttribute('role', 'form');
                            ?>
                            <?php echo $this->form()->openTag($form) ?>
                            <div class="form-group">
                                <?php
                                $email=$form->get('identity');
                                $email->setAttribute('type', 'email');
                                $email->setAttribute('placeholder', $email->getLabel());
                                $email->setAttribute('class', 'form-control');
                                ?>
                                <label for="identity" class="control-label"><?php echo $email->getLabel(); ?></label>
                                <?php echo $this->formInput($email) ?>
                            </div>
                            <div class="form-group">
                                <?php
                                $credential=$form->get('credential');
                                $credential->setAttribute('class', 'form-control');
                                ?>
                                <div class="form-group">
                                    <label for="credential" class="control-label"><?php echo $this->translate($credential->getLabel()); ?></label>
                                    <?php echo $this->formInput($credential) ?>
                                </div>
                            </div>
                            <?php
                            $submit=$form->get('submit');
                            $submit->setAttribute('class', 'btn  btn-info btn-block');
                            echo $this->formButton($submit)
                            ?>
                            <?php echo $this->form()->closeTag() ?>
                            <?php if ($this->enableRegistration) : ?>
                                Not registered? <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>">Sign up!</a>
                            <?php endif; ?>
                        </div>
                    </div>
                    <div class="col-xs-6">
                        <p class="lead"><?php echo $this->translate('Info'); ?> <span class="text-success"><?php echo $this->translate('for client'); ?></span></p>
                        <ul class="list-unstyled" style="line-height: 2">
                            <li><span class="fa fa-check text-success"></span>
                                <a href="#"  id="helpHref" data-href="<?php echo $this->url('application', array('action' => 'help', 'id' => '1')); ?>"><?php echo $this->translate('How to become a client'); ?></a></li>
                            <li><span class="fa fa-check text-success"></span><a href="/maketCT-1.xls"><?php echo $this->translate('Download the template'); ?></a></li>
                            <li><span class="fa fa-check text-success"></span><a href="http://mogilevcci.by" target="_blank"><?php echo $this->translate('Official site'); ?></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div id="loadImg">
                <div id="img">
                    <img src="<?php echo $this->basePath('/images/495.gif') ?>"/></div>
            </div>
        </div>
    </div>
</div>